src/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <description>Rating custom object to track the score of each document suggestion.</description>
    <label>Rating</label>
    <nameField>
        <label>Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Rating__c/fields/Document_id__c.field-meta.xml
<CustomField>
    <fullName>Document_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Document_id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/RatingsHandler.cls
public with sharing class RatingsHandler {
    @AuraEnabled(cacheable=false)
    public static Rating__c getRating(String documentId) {
        List<Rating__c> records = [
            SELECT Score__c, Document_id__c
            FROM Rating__c
            WHERE Document_id__c = :documentId
            LIMIT 1
        ];
        if (records.size() > 0) {
            return records[0];
        }
        return null;
    }
}