src/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <description>Rating custom object to track the score of each document suggestion.</description>
    <label>Rating</label>
    <nameField>
        <label>Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Rating__c/fields/Document_id__c.field-meta.xml
<CustomField>
    <fullName>Document_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Document_id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/RatingsHandlerTest.cls
@isTest
private class RatingsHandlerTest {
  @isTest
  static void testGetRatingWithExistingRecord() {
    Rating__c testRating = new Rating__c(
      Score__c = 90,
      Document_id__c = 'TestDocumentId'
    );
    insert testRating;

    Rating__c result = RatingsHandler.getRating('TestDocumentId');

    System.assertEquals(testRating.Id, result.Id, 'The Result Id received: ' + result.Id + ' was expected to be: ' + testRating.Id);
    System.assertEquals(testRating.Score__c, result.Score__c, 'The Result score received: ' + result.Score__c + ' was expected to be: 90');
    System.assertEquals(testRating.Document_id__c, result.Document_id__c, 'The Result document Id received: ' + result.Document_id__c + ' was expected to be: TestDocumentId');
  }

  @isTest
  static void testGetRatingWithNoRecord() {
    Rating__c testRating = RatingsHandler.getRating('NonExistentDocumentId');
    System.assertEquals(null, testRating, 'Test Rating received: ' + testRating + ' was expected to be null.');
  }
}